### ISSUE TITLE
Just checking to see if this is still supported

### ISSUE THREAD

**Issue by SunnyIzr** [thechrisoshow/promoter#1]
Hey Guys:

Just checking to see if this gem is still being supported. I'm getting some nasty errors after bundling seemingly related to the gem (invalid multibyte char (US-ASCII) (SyntaxError)).

Let me know.

-Sunny

**Comment by thechrisoshow** [comment]
Sure is supported! 

Interesting - I'll investigate. 
Are you getting the error when you just do a standard bundle install? 

What Ruby/Rails version are you on?

**Comment by SunnyIzr** [comment]
Hi Chris:

That's awesome to hear you're supporting! 

So the bundle goes through fine, it's when I start my rails console (following the bundle) where I get that error.

-Sunny

**Comment by thechrisoshow** [comment]
Hi Sunny, 

I think I've fixed the bug and deployed a new version 0.1.4. 

Update the gem and try that out. Let me know once it's fixed and I'll close this issue.

Thanks!
Chris
😎

**Comment by SunnyIzr** [comment]
Hi Chris:

Thanks so much. Appears to be working on my end!

Thanks,
Sunny

On Thu, Aug 20, 2015 at 9:59 AM, thechrisoshow notifications@github.com
wrote:

> Hi Sunny,
> 
> I think I've fixed the bug and deployed a new version 0.1.4.
> 
> Update the gem and try that out. Let me know once it's fixed and I'll
> close this issue.
> 
> Thanks!
> Chris
> 😎
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thechrisoshow/promoter/issues/1#issuecomment-133017996
> .

## 

________________________
_Sunny Israni_
_Zoraab_
_Co-Founder_
P: (201) 274-9118
E: Sunny@zoraab.com
www.zoraab.com
